# Generated by Django 3.1.5 on 2021-01-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210129_1402'),
        ('orders', '0002_auto_20210127_2334'),
    ]

    operations = [
    ]
