# Generated by Django 3.1.5 on 2021-01-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'category_products',
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'package_types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('point', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('ingredient', models.CharField(max_length=120)),
                ('sold_out', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sales_unit', models.CharField(max_length=120)),
                ('thumbnail', models.URLField(max_length=500)),
                ('delivery_type', models.CharField(default='샛별배송/택배배송', max_length=120)),
                ('information', models.TextField()),
                ('main_description', models.TextField()),
                ('detail_description', models.TextField()),
                ('discount_rate', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'product_groups',
            },
        ),
        migrations.CreateModel(
            name='ProductGroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'product_group_images',
            },
        ),
        migrations.CreateModel(
            name='ProductGroupPackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'product_group_package_types',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
