# Generated by Django 3.1.5 on 2021-01-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210129_1402'),
        ('products', '0003_productgroup_price'),
    ]

    operations = [
    ]
